### ISSUE TITLE
Title font not loaded

### ISSUE THREAD

**Issue by aminb** [DataHaskell/datahaskell.github.io#1]
The title (`.brand`) font is set to `Roboto Condensed` as per
in https://github.com/DataHaskell/datahaskell.github.io/blob/5b0495a699a4a99e9bcc1a606c1bb1055c119fcc/style.css#L18.

However, `materialize` doesn't ship `Roboto Condensed`. So, we should probably include it from Google Fonts ourselves.

**Comment by NickSeagull** [comment]
Somehow the font loads for me (maybe because I'm using Chrome?).

If you want you can include it from GFonts and do a PR :smile: @aminb

**Comment by aminb** [comment]
I'm pretty sure that's because you already have it installed on your system 😉

Here you go: #2 

P.S. It's probably a good idea to omit the carriage return characters in the end of lines. If you're on Windows, your editor should be able to take care of this.
